spring.application.name=motorCloud

# Configuración del servidor
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/motorCloud_db?createDatabaseIfNotExist=true
spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.h2.console.path=/h2-console

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# subida de archivos
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# EMAIL CONFIG
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=mango.store.thc@gmail.com
#spring.mail.password=iachamgjnmenbxxd
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Interfaz universal para escuchar en todas las interfaces de red disponibles.
server.address=0.0.0.0


